version: "3"
services:
  kodim:
    image: onset/kodimcz:0.0.2
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - ./:/content/kurzy/kurz
  mongo:
    image: mongo
    ports:
      - '27017:27017'
