name: Fixer

on:
  push:
    branches:
      - main

jobs:
  fix:
    name: Fix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier fix
        run: npm run fix
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Oprava podle pravidel Prettieru
          branch: pr/fix
          commit-message: Oprava pomocí `npm run fix`
