name: Quality assurance check

on: push

jobs:
  test:
    name: Quality assurance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run
        run: npm run quality-assurance
